//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Exam_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamSubmission
    {
        public int submission_id { get; set; }
        public Nullable<int> exam_id { get; set; }
        public Nullable<int> student_id { get; set; }
        public Nullable<int> question_id { get; set; }
        public Nullable<int> submitted_option_number { get; set; }
    
        public virtual ExamQuestion ExamQuestion { get; set; }
        public virtual Exam Exam { get; set; }
        public virtual Student Student { get; set; }
    }
}
