//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Exam_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.ExamSubmissions = new HashSet<ExamSubmission>();
        }
    
        public int student_id { get; set; }
        public string full_name { get; set; }
        public string username { get; set; }
        public string email_address { get; set; }
        public string mobile_number { get; set; }
        public string gender { get; set; }
        //public Nullable<System.DateTime> birth_date { get; set; }
        public DateTime birth_date { get; set; }
        public string city { get; set; }
        public string password { get; set; }
        public string photo { get; set; }

        public string Exam_Code { get; set; }   
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamSubmission> ExamSubmissions { get; set; }
    }
}
